// The stream event kinds this UI can name, and the line each one renders as.
// Remedy deliberately keeps this DATA separate from humanize.ts: the key set is
// pinned to the Python run-log emitters by
// tests/ui_contracts/test_humanize_catalog.py, which derives the same set with an
// AST walk and compares it to the keys scanned out of the lines below. Adding a
// Python emitter without adding an entry here goes red, and so does the reverse.
// A kind absent from this map is not dropped: humanize.ts renders it generically.
export const STREAM_EVENT_CATALOG: Readonly<Record<string, string>> = {
  "agent_loop_inspected": "The agent loop's current state was inspected.",
  "api_retry": "A provider API call failed and was retried.",
  "apply_dry_run_completed": "The apply dry run finished.",
  "apply_record_saved": "The durable record of an apply was saved.",
  "brain_node_inspected": "A node in the project brain was inspected.",
  "brain_viewer_prepared": "The brain viewer's data was prepared for display.",
  "budget.tick": "The job's budget spend was measured at a safe point.",
  "builder_bridge_intent_approved": "The builder's patch intent was approved.",
  "builder_bridge_test_completed": "The tests after the builder's patch finished.",
  "builder_completed": "The builder finished its work on the task.",
  "builder_output_received": "The builder's output came back from the provider.",
  "builder_patch_parsed": "The builder's patch was parsed.",
  "builder_prompt_created": "The builder's prompt was assembled.",
  "builder_started": "The builder started work on the task.",
  "command.accepted": "The command was accepted and queued for the run.",
  "context_coverage_inspected": "Context coverage was inspected for this task.",
  "continued_from_node": "The run continued from an earlier brain node.",
  "contract_decision": "A run contract decision was recorded.",
  "diff_repair_applied": "A diff repair was applied.",
  "diff_repair_not_used": "A diff repair was not used for this cycle.",
  "final_audit_completed": "The final audit finished.",
  "job_created": "The job was created.",
  "job_evidence_exported": "The job's evidence bundle was exported.",
  "job_flow_started": "The job flow started.",
  "job_planned": "The job was planned into tasks.",
  "job_stopped": "The job stopped.",
  "memory_learned": "Something was written to project memory.",
  "patch_intent_approved": "A patch intent was approved.",
  "patch_intent_created": "A patch intent was created.",
  "patch_intent_failed": "A patch intent failed to apply.",
  "patch_intent_rejected": "A patch intent was rejected.",
  "patch_intent_skipped": "A patch intent was skipped.",
  "planning_completed": "Planning finished and produced a task list.",
  "planning_failed": "Planning failed.",
  "planning_started": "Planning started.",
  "project_brain_inspected": "The project brain was inspected.",
  "project_constitution_loaded": "The project constitution was loaded.",
  "project_memory_recalled": "Project memory was recalled for this run.",
  "proof_collected": "Proof of the passing tests was collected.",
  "provider_error": "The provider reported an error.",
  "provider_result": "The provider returned its final result.",
  "repair_context_created": "The context for a repair was assembled.",
  "repair_loop_cycle_started": "A repair loop cycle started.",
  "repair_loop_stopped": "The repair loop stopped.",
  "repair_loop_succeeded": "The repair loop succeeded.",
  "repair_mode_selected": "The repair mode was chosen for this cycle.",
  "repair_output_received": "The repair agent's output came back from the provider.",
  "repair_prompt_created": "The repair prompt was assembled.",
  "repair_round_fell_back_to_full_file": "The repair round fell back to rewriting the whole file.",
  "repair_task_created": "A repair task was created from a review finding.",
  "repo_application_completed": "The changes were applied to the repository.",
  "repo_application_skipped": "Applying the changes to the repository was skipped.",
  "resume_blocked": "Resuming the run was blocked.",
  "resume_completed": "The run resumed and finished.",
  "resume_started": "Resuming the run started.",
  "resume_test_completed": "The resume test finished.",
  "resume_test_started": "The resume test started.",
  "revert_blocked": "Reverting the apply was blocked.",
  "revert_completed": "Reverting the apply finished.",
  "revert_failed": "Reverting the apply failed.",
  "revert_started": "Reverting the apply started.",
  "review_finding_opened": "The reviewer opened a finding.",
  "review_finding_rechecked": "A review finding was rechecked.",
  "reviewer_output_received": "The reviewer's output came back from the provider.",
  "reviewer_prompt_created": "The reviewer's prompt was assembled.",
  "run_usage_recorded": "The run's usage was recorded.",
  "snapshot_create_completed": "The repository snapshot was created.",
  "snapshot_verified": "The repository snapshot was verified.",
  "source_patch_applied": "A source patch was applied.",
  "stream_cap_reached": "The stream hit its size cap and stopped recording.",
  "task_gate_evaluated": "The task's gate was evaluated.",
  "task_round_completed": "A review round of a task finished.",
  "task_run_completed": "A task finished.",
  "task_run_failed": "A task failed.",
  "task_run_noop": "A task ran and changed nothing.",
  "task_run_started": "A task started.",
  "task_started": "A task started, as the run trace records it.",
  "task_workspace_applied": "The task's workspace changes were applied.",
  "test_failure_artifact_created": "A test failure artifact was saved.",
  "test_run_blocked": "The test run was blocked.",
  "test_run_completed": "The test run finished.",
  "test_run_requested": "A test run was requested.",
  "test_run_started": "The test run started.",
  "test_run_timed_out": "The test run timed out.",
  "token_policy_applied": "The token policy was applied to the prompt.",
  "tool_result": "A tool returned its result.",
  "tool_use": "The agent used a tool.",
  "verification_failed": "Verification failed.",
  "verification_passed": "Verification passed.",
  "workspace_materialized": "The workspace was prepared for this run.",
  "worktree_prepared": "A git worktree was prepared for the task.",
  "worktree_recovered": "The interrupted run's git worktree was recovered.",
  "worktree_retained": "The git worktree was kept for inspection.",
};
