// The stream event kinds this UI can name, and the line each one renders as.
// Remedy deliberately keeps this DATA separate from humanize.ts: the key set is
// pinned to the Python run-log emitters by
// tests/ui_contracts/test_humanize_catalog.py, which derives the same set with an
// AST walk and compares it to the keys scanned out of the lines below. Adding a
// Python emitter without adding an entry here goes red, and so does the reverse.
// A kind absent from this map is not dropped: humanize.ts renders it generically.
export const STREAM_EVENT_CATALOG: Readonly<Record<string, string>> = {
  "agent_loop_cycle_decision": "The agent loop decided what to do next in this cycle.",
  "agent_loop_inspected": "The agent loop's current state was inspected.",
  "agent_loop_stopped": "The agent loop stopped.",
  "api_retry": "A provider API call failed and was retried.",
  "brain_node_inspected": "A node in the project brain was inspected.",
  "brain_viewer_prepared": "The brain viewer's data was prepared for display.",
  "budget.tick": "The job's budget spend was measured at a safe point.",
  "builder_completed": "The builder finished its work on the task.",
  "builder_output_received": "The builder's output came back from the provider.",
  "builder_prompt_created": "The builder's prompt was assembled.",
  "builder_started": "The builder started work on the task.",
  "command.accepted": "The command was accepted and queued for the run.",
  "context_budget_optimized": "The context budget was optimized to fit the prompt.",
  "context_coverage_inspected": "Context coverage was inspected for this task.",
  "context_pack_created": "A context pack was assembled for the prompt.",
  "continued_from_node": "The run continued from an earlier brain node.",
  "contract_decision": "A run contract decision was recorded.",
  "dod_gate_evaluated": "The definition-of-done gate was evaluated.",
  "final_audit_completed": "The final audit finished.",
  "fulfillment_completed": "Fulfillment finished.",
  "fulfillment_proof_built": "The fulfillment proof was built.",
  "fulfillment_staged_apply": "Fulfillment applied its changes to the staging area.",
  "fulfillment_started": "Fulfillment started.",
  "git_status_read": "The repository's git status was read.",
  "job_created": "The job was created.",
  "job_evidence_exported": "The job's evidence bundle was exported.",
  "job_flow_started": "The job flow started.",
  "job_planned": "The job was planned into tasks.",
  "job_stopped": "The job stopped.",
  "memory_learned": "Something was written to project memory.",
  "patch_intent_approved": "A patch intent was approved.",
  "patch_intent_created": "A patch intent was created.",
  "patch_intent_failed": "A patch intent failed to apply.",
  "patch_intent_rejected": "A patch intent was rejected.",
  "patch_intent_skipped": "A patch intent was skipped.",
  "planning_completed": "Planning finished and produced a task list.",
  "planning_failed": "Planning failed.",
  "planning_started": "Planning started.",
  "project_brain_inspected": "The project brain was inspected.",
  "project_constitution_loaded": "The project constitution was loaded.",
  "project_memory_recalled": "Project memory was recalled for this run.",
  "promotion_dry_run_completed": "The promotion dry run finished.",
  "provider_error": "The provider reported an error.",
  "provider_result": "The provider returned its final result.",
  "readiness_assessed": "The project's readiness was assessed.",
  "repair_loop_stopped": "The repair loop stopped.",
  "repair_output_received": "The repair agent's output came back from the provider.",
  "repair_prompt_created": "The repair prompt was assembled.",
  "repair_task_created": "A repair task was created from a review finding.",
  "repo_application_completed": "The changes were applied to the repository.",
  "repo_application_skipped": "Applying the changes to the repository was skipped.",
  "resume_blocked": "Resuming the run was blocked.",
  "resume_completed": "The run resumed and finished.",
  "resume_started": "Resuming the run started.",
  "resume_test_completed": "The resume test finished.",
  "resume_test_started": "The resume test started.",
  "review_finding_opened": "The reviewer opened a finding.",
  "review_finding_rechecked": "A review finding was rechecked.",
  "reviewer_output_received": "The reviewer's output came back from the provider.",
  "reviewer_prompt_created": "The reviewer's prompt was assembled.",
  "run_contract_inspected": "The run contract was inspected.",
  "source_context_injected": "Source context was injected into the prompt.",
  "source_patch_applied": "A source patch was applied.",
  "staging_created": "A staging area was created for the run.",
  "staging_promoted": "The staging area was promoted.",
  "stream_cap_reached": "The stream hit its size cap and stopped recording.",
  "task_execution_started": "Task execution started.",
  "task_gate_evaluated": "The task's gate was evaluated.",
  "task_run_completed": "A task finished.",
  "task_run_failed": "A task failed.",
  "task_run_noop": "A task ran and changed nothing.",
  "task_run_started": "A task started.",
  "task_started": "A task started, as the run trace records it.",
  "task_workspace_applied": "The task's workspace changes were applied.",
  "test_failure_artifact_created": "A test failure artifact was saved.",
  "token_policy_applied": "The token policy was applied to the prompt.",
  "token_policy_inspected": "The token policy was inspected.",
  "tool_result": "A tool returned its result.",
  "tool_use": "The agent used a tool.",
  "verification_failed": "Verification failed.",
  "verification_passed": "Verification passed.",
  "workspace_materialized": "The workspace was prepared for this run.",
  "worktree_prepared": "A git worktree was prepared for the task.",
  "worktree_retained": "The git worktree was kept for inspection.",
};
