"""Guards for the hash-pinned toolchain CI installs (T2_F279 T002, DECISION F279 D1).

`constraints.txt` is GENERATED by the `uv pip compile` command its own header records, and is
never edited by hand. These guards read it as text and check what the generator cannot check
for itself: that it still covers what `pyproject.toml` declares, that every pin carries a hash,
that the linter it pins is the linter the zero-findings lint gate is pinned to, and that the
command it was made by is the command this feature ruled. None of them needs the network.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - the 3.10 column reads the same file through the backport
    import tomli as tomllib

REPO_ROOT = Path(__file__).resolve().parents[2]
CONSTRAINTS_PATH = REPO_ROOT / "constraints.txt"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
EXTRAS_CI_INSTALLS = ("dev", "ollama")
HASH_PATTERN = re.compile(r"--hash=sha256:[0-9a-f]{64}\b")
PIN_PATTERN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)")


def constraints_text() -> str:
    return CONSTRAINTS_PATH.read_text(encoding="utf-8")


def pinned_entries() -> list[tuple[str, str, str]]:
    """(canonical name, version, whole entry text) for every pin, hash lines included."""
    entries: list[tuple[str, str, str]] = []
    for block in re.split(r"\n(?=[A-Za-z0-9])", constraints_text()):
        match = PIN_PATTERN.match(block)
        if match:
            entries.append((canonicalize_name(match.group(1)), match.group(2), block))
    return entries


def pinned_versions() -> dict[str, str]:
    return {name: version for name, version, _ in pinned_entries()}


def project_table() -> dict:
    return tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))["project"]


def declared_requirements() -> list[Requirement]:
    """Remedy's own dependencies plus the extras CI installs, as `pyproject.toml` declares them."""
    project = project_table()
    declared = list(project["dependencies"])
    for extra in EXTRAS_CI_INSTALLS:
        declared.extend(project["optional-dependencies"][extra])
    return [Requirement(text) for text in declared]


def test_the_constraints_file_exists_and_pins_something():
    assert CONSTRAINTS_PATH.is_file(), CONSTRAINTS_PATH
    assert len(pinned_entries()) > len(declared_requirements())


def test_every_pin_is_exact_and_carries_a_hash():
    """One unhashed pin is enough for pip to refuse the whole hash-checked install."""
    for name, version, entry in pinned_entries():
        assert HASH_PATTERN.search(entry), f"{name}=={version} carries no sha256 hash"


def test_every_declared_dependency_is_pinned_inside_its_declared_range():
    """`pip install --no-deps -e .` resolves nothing, so the pinned set must cover the declaration."""
    pins = pinned_versions()
    for requirement in declared_requirements():
        name = canonicalize_name(requirement.name)
        assert name in pins, f"{requirement} is declared in pyproject.toml but not pinned"
        assert requirement.specifier.contains(pins[name], prereleases=True), (
            f"{name}=={pins[name]} is outside the declared range {requirement}")


def test_the_pinned_ruff_is_the_ruff_the_lint_gate_is_pinned_to():
    """DECISION F279 D1 (3): the linter CI installs is the one `pyproject.toml` pins with `==`."""
    dev = [Requirement(text) for text in project_table()["optional-dependencies"]["dev"]]
    ruff = [requirement for requirement in dev if canonicalize_name(requirement.name) == "ruff"]
    assert len(ruff) == 1
    specifiers = list(ruff[0].specifier)
    assert len(specifiers) == 1 and specifiers[0].operator == "==", ruff[0]
    assert pinned_versions()["ruff"] == specifiers[0].version


def test_the_runtime_dependencies_carry_an_upper_bound():
    """A new major version of `pydantic` or `psutil` arrives by a decision, never unannounced."""
    for requirement in declared_requirements():
        if canonicalize_name(requirement.name) in {"pydantic", "psutil"}:
            assert any(spec.operator == "<" for spec in requirement.specifier), requirement


def test_the_header_records_the_ruled_generator_command():
    """The file is reproducible only if the command that made it is on disk beside it."""
    header = constraints_text().splitlines()[:2]
    assert header[0] == "# This file was autogenerated by uv via the following command:"
    command = header[1].removeprefix("#    ").split()
    assert command[:4] == ["uv", "pip", "compile", "pyproject.toml"]
    for flag in ("--universal", "--generate-hashes", "--exclude-newer"):
        assert flag in command, flag
    floor = re.fullmatch(r">=(\d+\.\d+)", project_table()["requires-python"])
    assert floor is not None
    assert command[command.index("--python-version") + 1] == floor.group(1)
    extras = {command[i + 1] for i, token in enumerate(command) if token == "--extra"}
    assert extras == set(EXTRAS_CI_INSTALLS)
    assert command[-2:] == ["-o", "constraints.txt"]
