"""`docs/guides/environment.md` is the variable registry rendered, and it is indexed (T2_F279 T001).

The guide is GENERATED by `render_environment_guide()` in `packages/orchestration/config.py`.
A registry change that is not re-rendered leaves a guide that lists a variable Remedy no longer
reads or misses one it does, which is exactly the drift T001 exists to end, so the committed
bytes must equal the rendering.
"""
from __future__ import annotations

from pathlib import Path

from packages.orchestration.config import (
    ENVIRONMENT_GUIDE_PATH,
    all_key_specs,
    render_environment_guide,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
GUIDE = REPO_ROOT / ENVIRONMENT_GUIDE_PATH
REGENERATE = ('python3 -c "from packages.orchestration.config import write_environment_guide; '
              'write_environment_guide()"')


def test_the_committed_guide_is_the_registry_rendered():
    assert GUIDE.is_file(), GUIDE
    assert GUIDE.read_text(encoding="utf-8") == render_environment_guide(), (
        f"{ENVIRONMENT_GUIDE_PATH} differs from the registry; regenerate it with {REGENERATE}")


def test_the_guide_lists_every_registered_variable_once():
    text = GUIDE.read_text(encoding="utf-8")
    for spec in all_key_specs():
        assert text.count(f"| `{spec.env_var}` |") == 1, spec.env_var


def test_the_guide_is_indexed_in_both_tables_of_the_docs_index():
    index = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")
    assert index.count("](guides/environment.md)") == 2
