#!/usr/bin/env python3
"""Round 20 — the fail-closed, staged-source, directed-hash-chain ZIP construction stage.

Invoked by ``make_review_zip.sh`` AFTER Evidence has been safely staged. Everything it reads is a
staged byte (Subject, Content-Proof, Final-Verifier, Change-Provenance, Commit-Chain), never the
original ``EVIDENCE_DIR``. It:

* strict-decodes the ReviewSubject (fail-closed) and the ContentProofV1 authority (mandatory when a
  Subject is declared — no fail-open empty authority);
* proves the authority set EQUALS the Final-Verifier authoritative set, the Change-Provenance
  covered set, and the attestable Subject paths;
* builds ONE typed ArchivePlan, then SNAPSHOTS every source member's bytes once (anchored no-follow)
  so the bytes packaged and the bytes hashed are the same;
* fills every source member's expected hash into the CoreArchivePlan, then emits the directed chain
  ``review_archive_plan.json → review_zip_expectation.json → .review_zip_manifest.json`` as
  in-memory generated bytes (no artifact hashes itself, none is reopened by path);
* builds the deterministic ZIP from the immutable bytes and reopens it to verify the exact typed
  membership. Any block, escape, mismatch, or authority disagreement is a hard failure.
"""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from packages.orchestration.archive_plan import (  # noqa: E402
    ArchivePlanError,
    build_archive_plan,
)
from packages.orchestration.review_zip import (  # noqa: E402
    ReviewZipError,
    build_review_zip_from_snapshot,
    read_nul_list,
    snapshot_plan_members,
    verify_review_zip,
)


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


#: Round 34 F1: the closed set of package statuses a build can publish under. Every candidate final
#: path (the template realized for each status) is declared as a generated output so the dirty-subject
#: disposition never self-blocks, regardless of which status the verified manifest yields.
_CANDIDATE_STATUSES = (
    "READY_FOR_REVIEW", "READY_FOR_REVIEW_UNVERIFIED", "BLOCKED_EVIDENCE", "NO_EVIDENCE", "UNKNOWN",
)


def _final_path_for(final_template: str, package_status: str) -> str:
    """Realize the final-name TEMPLATE for one package status (``{package_status}`` placeholder)."""
    return final_template.replace("{package_status}", package_status)


def _reported_final_path(final_path: str, repo_root: str) -> str:
    """The published path as the shell should name it: repository-root-relative while the package is
    published INSIDE the repository, and absolute once it is published to the operator's archive
    outside it (package-hygiene amendment, 2026-08-23). A `../..`-style relative path would be
    correct only for a caller whose cwd is the repository root, so it is never reported."""
    ap = os.path.abspath(final_path)
    root = os.path.abspath(repo_root)
    if ap == root or ap.startswith(root + os.sep):
        return os.path.relpath(ap, root).replace(os.sep, "/")
    return ap


def _derive_generated_outputs(brm, repo_root: str, outputs, manifest_rel: str) -> frozenset:
    """F3 (round 29) / F1 (round 34): the exact repository-ROOT-relative outputs THIS invocation
    generates — every candidate final ZIP path (the status-name template realized for each possible
    status) plus the root manifest it emits — resolved to repo-root-relative form and filtered to the
    eligible packaging-output shape. Anything outside the repository root, or not a packaging-output
    shape, is dropped. This is the SOLE authority for the dirty-subject disposition; there is no
    caller-supplied free list."""
    root = os.path.abspath(repo_root)
    result = set()
    raws = list(outputs) if not isinstance(outputs, str) else [outputs]
    for raw in [*raws, manifest_rel]:
        if not raw:
            continue
        ap = raw if os.path.isabs(raw) else os.path.join(root, raw)
        try:
            rel = os.path.relpath(os.path.abspath(ap), root).replace(os.sep, "/")
        except ValueError:
            continue
        if brm._eligible_generated_output(rel):
            result.add(rel)
    return frozenset(result)


def _strict_loads(raw, where: str):
    """F5 (round 25/26): decode a staged trust-path artifact with the ONE shared strict decoder
    (``packages.common.strict_json``). A duplicate key at ANY depth (or NaN/Infinity/bad UTF-8)
    raises ArchivePlanError and BLOCKS the package rather than silently collapsing to the stdlib's
    last-wins value."""
    from packages.common.strict_json import StrictJsonError, strict_loads
    try:
        return strict_loads(raw, where=where)
    except StrictJsonError as exc:
        raise ArchivePlanError(f"{where} is not valid/unambiguous JSON: {exc}") from None


class _StagedArtifacts:
    """F5 (round 21): the ONE immutable staged byte map. Each root artifact is read from the staging
    snapshot EXACTLY ONCE; objects are decoded from these bytes and the Plan's evidence members carry
    these exact shas, so `snapshot_plan_members` refuses if a staged file changed between decode and
    package — decode-bytes and package-bytes are provably identical."""

    def __init__(self, evidence_root: str | None, current_prefix: str, budget=None):
        from packages.common.acquisition_budget import AcquisitionBudget
        self.by_arcname: dict[str, tuple[bytes, str]] = {}     # arcname -> (bytes, sha256)
        self._root = evidence_root
        self._prefix = current_prefix
        # F4 (round 26): the ONE shared acquisition budget — per-member + aggregate + count. A
        # cached re-read is served from by_arcname and does NOT recharge.
        self._budget = budget if budget is not None else AcquisitionBudget()

    def load(self, name: str) -> tuple[bytes | None, str]:
        """Read `<prefix>/<name>` once (bytes, sha). GENUINELY ABSENT or a refused symlink/unsafe
        kind -> (None, ""). A budget overflow or a mid-read integrity failure BLOCKS (raises).

        F6 (round 25): the read goes through the shared ANCHORED, O_NOFOLLOW ``secure_fs`` primitives
        — never ``os.path.isfile`` + ``open`` by name. A symlink (or a regular file swapped to one)
        is refused, reading no outside bytes.

        F3 (round 27): the byte budget is charged from a TRUSTWORTHY anchored no-follow ``lstat`` size
        BEFORE any bytes are read, so a per-member or aggregate OVERFLOW blocks here and can never be
        translated into a silent absence — the Round-26 bug where the bounded read rejected an
        over-limit member as ``SecureFsError`` and ``load`` returned ``(None, "")``. Absence,
        symlink/unsafe-kind, budget overflow and a between-observation-and-read change are all
        distinguished."""
        if not self._root:
            return None, ""
        arc = f"{self._prefix}/{name}"
        if arc in self.by_arcname:
            return self.by_arcname[arc]                 # cached — do not recharge
        import stat as _stat

        from packages.common import secure_fs
        from packages.common.acquisition_budget import AcquisitionBudgetError
        try:
            parent_fd, base = secure_fs.open_anchored_parent(
                self._root, arc, noun="staged evidence artifact")
        except secure_fs.SecureFsError:
            return None, ""                             # a missing parent directory — genuinely absent
        try:
            try:
                pre = os.stat(base, dir_fd=parent_fd, follow_symlinks=False)
            except FileNotFoundError:
                return None, ""                         # genuinely absent
            if _stat.S_ISLNK(pre.st_mode) or not _stat.S_ISREG(pre.st_mode):
                return None, ""                         # refused symlink / non-regular kind
            # Charge from the trusted anchored size BEFORE reading — an over-limit member BLOCKS.
            try:
                self._budget.charge(arc, pre.st_size)
            except AcquisitionBudgetError as exc:
                raise ArchivePlanError(f"staged acquisition budget exceeded: {exc}") from None
            try:
                vf = secure_fs.read_verified_file_at(
                    parent_fd, base, expected_kind="regular", max_bytes=pre.st_size + 1,
                    noun="staged evidence artifact")
            except secure_fs.SecureFsError as exc:
                # The file was swapped/grew/torn between the trusted stat and the read — an integrity
                # failure on a member we already committed to, NOT an absence.
                raise ArchivePlanError(
                    f"staged evidence artifact {name!r} changed during acquisition: {exc}") from None
        finally:
            os.close(parent_fd)
        rec = (vf.data, _sha256_hex(vf.data))
        self.by_arcname[arc] = rec
        return rec

    def load_json(self, name: str):
        raw, _ = self.load(name)
        if raw is None:
            return None
        return _strict_loads(raw, f"staged {name}")


def _decode_subject(raw: bytes | None):
    """Fail closed. No bytes -> legacy empty subject. Invalid JSON or schema failure BLOCKS."""
    from packages.orchestration.review_subject import (
        ReviewSubjectV1,
        decode_review_subject_from_json,
    )
    if raw is None:
        return ReviewSubjectV1()
    d = _strict_loads(raw, "the declared review subject")
    return decode_review_subject_from_json(d)


def _decode_content_proof(raw: bytes | None, *, subject_declared: bool):
    """F2/F3 (round 20/21): the ONE authority source, strict-decoded. When a Subject is DECLARED the
    proof is MANDATORY (even with zero files); a missing/invalid/schema-failing proof BLOCKS."""
    from packages.orchestration.review_subject import decode_content_proof_v1
    if raw is None:
        if subject_declared:
            raise ArchivePlanError(
                "a ReviewSubject is declared but the Content Proof is absent — the authority set "
                "cannot be derived and the package is refused")
        return None
    d = _strict_loads(raw, "the Content Proof")
    return decode_content_proof_v1(d)     # raises ContentProofError on schema failure


def _assert_authority_equality(*, authority: set, subject, content_proof, staged) -> None:
    """F2 (round 20): authority MUST equal every other authoritative set — all decoded from the ONE
    staged byte map (F5). Any disagreement blocks."""
    from packages.orchestration.repair_attest import is_attestable_source

    if content_proof is not None:
        if authority != content_proof.authority_paths():
            raise ArchivePlanError("authority set != Content-Proof file+tombstone paths")
        if content_proof.base_commit != subject.base_commit \
                or content_proof.head_commit != subject.head_commit:
            raise ArchivePlanError("Content-Proof base/head != ReviewSubject base/head")

    attestable_subject = {f.path for f in subject.files if is_attestable_source(f.path)}
    if authority != attestable_subject:
        only_auth = sorted(authority - attestable_subject)[:4]
        only_subj = sorted(attestable_subject - authority)[:4]
        raise ArchivePlanError(
            f"authority set != attestable ReviewSubject paths "
            f"(only_in_authority={only_auth}, only_in_subject={only_subj})")

    fv = staged.load_json("final_verifier_report.json")
    if fv is not None:
        if authority != set(fv.get("authoritative_changed_files") or []):
            raise ArchivePlanError("authority set != Final-Verifier authoritative_changed_files")
    cpg = staged.load_json("change_provenance_gate.json")
    if cpg is not None:
        if authority != set(cpg.get("covered_files") or []):
            raise ArchivePlanError("authority set != Change-Provenance covered_files")


def _bind_staged_expected_hashes(plan, by_arcname: dict):
    """F5: set each pre-read staged artifact's decode-time sha as its plan evidence member's expected
    hash, so the snapshot read that packages it must reproduce the exact bytes that were decoded."""
    def _fill(members):
        out = []
        for m in members:
            rec = by_arcname.get(m.archive_path)
            if rec is not None and m.kind == "regular":
                out.append(dataclasses.replace(m, expected_sha256=rec[1]))
            else:
                out.append(m)
        return tuple(out)
    return dataclasses.replace(plan, evidence_members=_fill(plan.evidence_members))


def _finalize_plan(plan, snapshot):
    """Fill every SOURCE member's expected content identity from the immutable snapshot, so the
    packaged CoreArchivePlan lets a ZIP-only reviewer recompute every source member's hash."""
    def _fill(members):
        out = []
        for m in members:
            snap = snapshot.get(m.archive_path)
            if snap is None:
                out.append(m)
                continue
            out.append(dataclasses.replace(
                m, expected_sha256=(None if snap.kind == "symlink" else snap.sha256),
                expected_link_target=(snap.link_target if snap.kind == "symlink" else None),
                expected_size=len(snap.data)))     # F4 (round 23): bind the exact byte length
        return tuple(out)
    return dataclasses.replace(plan, repository_members=_fill(plan.repository_members),
                               evidence_members=_fill(plan.evidence_members))


def _expected_model(snapshot, gen_hashes: dict) -> list:
    """The full expected member model (source + generated) a reviewer verifies, sorted by name."""
    rows = []
    for name in sorted(snapshot):
        m = snapshot[name]
        rows.append({"archive_path": name, "kind": m.kind, "mode": m.mode,
                     "sha256": m.sha256, "link_target": m.link_target,
                     "authoritative": m.authoritative})
    for name in sorted(gen_hashes):
        rows.append({"archive_path": name, "kind": "regular", "mode": 0o644,
                     "sha256": gen_hashes[name], "link_target": None, "authoritative": False})
    return sorted(rows, key=lambda r: r["archive_path"])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--final-template", required=True,
                    help="final publication path template containing the {package_status} placeholder; "
                         "the coordinator derives the exact status-bearing final path from the verified "
                         "manifest and publishes its private .part directly to it (no public intermediate)")
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--repo-files0", required=True, help="NUL-delimited repo context file list")
    ap.add_argument("--evidence-root", default="", help="the STAGING root (single byte source)")
    ap.add_argument("--evidence-files0", default="", help="NUL-delimited staged evidence file list")
    ap.add_argument("--subject-json", default="", help="STAGED review_subject.json")
    ap.add_argument("--content-proof-json", default="", help="STAGED content proof (authority)")
    ap.add_argument("--current-prefix", default="evidence/current")
    ap.add_argument("--plan-out", default="", help="where to also write review_archive_plan.json")
    ap.add_argument("--manifest-rel", required=True)
    ap.add_argument("--manifest-disk", required=True)
    # F3 (round 23): the coordinator rebuilds the Root Manifest from the SAME staged bytes it
    # packages, so no evidence artifact is interpreted from one read and packaged from another.
    ap.add_argument("--selection-mode", default="")
    ap.add_argument("--selection-reason", default="")
    ap.add_argument("--candidate-count", type=int, default=0)
    ap.add_argument("--rejected-candidate-count", type=int, default=0)
    ap.add_argument("--selected-mtime", default="")
    args = ap.parse_args()

    repo_files = read_nul_list(args.repo_files0)
    evidence_files = read_nul_list(args.evidence_files0) if args.evidence_files0 else []
    evidence_root = args.evidence_root or None

    try:
        # F5 — read the root artifacts from the ONE immutable staged byte map (once each).
        # F2 (round 22) — the SAME map also owns the gate bytes and the snapshot inventory, so the
        # READY decision and the packaged bytes are one and the same.
        staged = _StagedArtifacts(evidence_root, args.current_prefix)
        subject_bytes, subject_sha = staged.load("review_subject.json")
        proof_bytes, proof_sha = staged.load("current_change_content_proof.json")
        _, chain_sha = staged.load("review_commit_chain.json")
        SNAPSHOT_INVENTORY_NAME = ""
        if evidence_root:
            from packages.orchestration.evidence_inventory import SNAPSHOT_INVENTORY_NAME
            for _gate in ("final_verifier_report.json", "fresh_evidence_gate.json",
                          "artifact_contract_gate.json", "change_provenance_gate.json",
                          "runtime_integration_gate.json", "manifest_integrity.json",
                          "postmortem_integrity.json"):
                staged.load(_gate)                          # bind each gate's bytes into the map
            staged.load(SNAPSHOT_INVENTORY_NAME)

        subject = _decode_subject(subject_bytes)
        # F3 — a Subject is declared by its base declaration, not by having files; a declared
        # zero-file / net-zero / revert subject still requires a strict Proof.
        subject_declared = subject.declared
        content_proof = _decode_content_proof(proof_bytes, subject_declared=subject_declared)
        authority = content_proof.authority_paths() if content_proof is not None else set()

        if subject_declared:
            _assert_authority_equality(authority=authority, subject=subject,
                                       content_proof=content_proof, staged=staged)

        # F2 — the plan's subject identity is the RAW packaged Subject bytes' sha256.
        plan = build_archive_plan(
            repo_root=args.repo_root, subject=subject, repo_context_rel=repo_files,
            evidence_root=evidence_root, evidence_rel=evidence_files,
            authoritative_paths=authority,
            review_subject_raw_sha256=(subject_sha or None))

        # F5 — bind every pre-read staged artifact's decode-time sha into its plan evidence member,
        # so snapshot_plan_members REFUSES if the staged file changed between decode and package.
        plan = _bind_staged_expected_hashes(plan, staged.by_arcname)

        # Phase 1 — snapshot every source member once (anchored no-follow, verified).
        snapshot = snapshot_plan_members(plan)

        generated: dict = {}
        gen_hashes: dict = {}
        verified_status = {"package_status": "NO_EVIDENCE", "evidence_authoritative": False,
                           "review_subject_alignment": "absent", "manifest_sha256": ""}
        if args.plan_out and evidence_root:
            base = os.path.dirname(args.plan_out)
            plan_rel = os.path.relpath(args.plan_out, evidence_root)
            expect_disk = os.path.join(base, "review_zip_expectation.json")
            expect_rel = os.path.relpath(expect_disk, evidence_root)
            manifest_rel = args.manifest_rel

            # Phase 2 — the CoreArchivePlan: every SOURCE member with its expected hash.
            finalized = _finalize_plan(plan, snapshot)
            plan_bytes = (json.dumps(finalized.to_json(), indent=2, sort_keys=True) + "\n").encode()
            sha_plan = _sha256_hex(plan_bytes)

            # F1/F2 (round 22) — re-evaluate the READY gate matrix on the SAME staged byte map that
            # is packaged, and F3 — validate the snapshot inventory bijection against the finalized
            # plan. A blocking gate or an invalid inventory forces BLOCKED_EVIDENCE, and the gate
            # bytes were bound into the plan's evidence members so a mutation between decode and
            # package is refused by snapshot_plan_members above.
            import importlib.util as _ilu
            _spec = _ilu.spec_from_file_location(
                "_brm_gates", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                           "build_review_manifest.py"))
            _brm = _ilu.module_from_spec(_spec)
            _spec.loader.exec_module(_brm)
            gate_matrix = _brm.evaluate_ready_gate_matrix(staged.load_json)
            _staged_current = os.path.join(evidence_root, args.current_prefix)

            from packages.orchestration.evidence_inventory import (
                validate_snapshot_inventory,
            )
            obs_index_arc = f"{args.current_prefix}/self_run_observability_index.json"
            inventory_arc = f"{args.current_prefix}/{SNAPSHOT_INVENTORY_NAME}"
            inv = staged.load_json(SNAPSHOT_INVENTORY_NAME)
            inventory_problems: list = []
            if inv is not None:
                inventory_problems = validate_snapshot_inventory(
                    inv, finalized, prefix=args.current_prefix,
                    generated_outside_boundary={obs_index_arc, inventory_arc})
            elif finalized.evidence_members:
                inventory_problems = ["evidence_snapshot_inventory.json is missing"]
            status_blockers = list(gate_matrix["blocking_reasons"]) + inventory_problems

            # Phase 3 — the expectation artifact carries plan_sha256 + the full expected model.
            # F2 — every *_sha256 here is the RAW packaged bytes' sha (subject/proof from the one
            # staged byte map), never a reserialized projection.
            expect = {
                "expectation_v": 1,
                "verifier": "review_zip.verify_review_zip/round21",
                "review_archive_plan_sha256": sha_plan,
                "review_subject_sha256": subject_sha,
                "content_proof_sha256": proof_sha,
                "authority_set_sha256": _sha256_hex(
                    json.dumps(sorted(authority)).encode()),
                "expected_member_count": len(snapshot) + 3,   # sources + plan + expectation + manifest
                "authoritative_member_count": sum(1 for m in snapshot.values() if m.authoritative),
                "symlink_member_count": sum(1 for m in snapshot.values() if m.kind == "symlink"),
                "tombstone_count": len(plan.tombstones),
                "generated_artifacts": sorted([plan_rel, expect_rel, manifest_rel]),
                "expected_members": _expected_model(snapshot, {}),
                "tombstones": [t.to_json() for t in plan.tombstones],
            }
            expect_bytes = (json.dumps(expect, indent=2, sort_keys=True) + "\n").encode()
            sha_expect = _sha256_hex(expect_bytes)

            # F4 — the commit-chain sha is the RAW packaged bytes' sha, from the staged map.
            commit_chain_sha = chain_sha
            # F6 (round 32) — the patchset identity is bound to (commit, exact archive path, patch sha)
            # ordered records derived from review_commit_chain.json. Only exact members under
            # <prefix>/review_commit_patches/<sha>.patch count; an ordinary source/test filename that
            # merely contains "commit_patch" can never enter the identity, and a missing/extra patch
            # blocks.
            from packages.orchestration.review_subject import commit_patchset_identity
            _chain_doc = staged.load_json("review_commit_chain.json")
            _snap_sha = {arc: m.sha256 for arc, m in snapshot.items()}
            _patchset = commit_patchset_identity(
                _chain_doc if isinstance(_chain_doc, dict) else {}, _snap_sha, args.current_prefix)
            patchset_sha = _patchset["sha256"]
            status_blockers = status_blockers + _patchset["problems"]   # a bad patchset BLOCKS

            # F6 (round 24) — build the Root Manifest from the IMMUTABLE Source snapshot bytes this
            # process packages, NOT from a fresh re-read of the staged evidence tree. The snapshot
            # was anchored/verified once above; every Evidence fact in the manifest therefore comes
            # from exactly the bytes the ZIP carries, so no artifact can be interpreted from one read
            # and packaged from another, and no staging-filesystem race can slip between them.
            evidence_view = _brm._view_from_snapshot(snapshot, args.current_prefix)
            # F3 (round 29): the generated-output set is DERIVED from THIS coordinator's own concrete
            # outputs (the ZIP it writes and the root manifest it emits), never a caller-supplied free
            # list, and each is filtered to the eligible packaging-output shape. A caller cannot name
            # an arbitrary source path here and have it hidden from the dirty subject.
            _candidate_finals = [_final_path_for(args.final_template, s)
                                 for s in _CANDIDATE_STATUSES]
            generated_outputs = _derive_generated_outputs(_brm, args.repo_root,
                                                          _candidate_finals, args.manifest_rel)
            base_manifest = _brm.build_manifest_from_snapshot(
                evidence_view, evidence_path=_staged_current,
                selection_mode=args.selection_mode,
                selection_reason=args.selection_reason, candidate_count=args.candidate_count,
                rejected_candidate_count=args.rejected_candidate_count,
                selected_mtime=args.selected_mtime,
                generated_outputs=generated_outputs)
            # F1/F3 — the FINAL status is the manifest's status ONLY when the gate matrix and the
            # snapshot inventory (decoded from the packaged bytes) also pass; else BLOCKED_EVIDENCE.
            _ms = base_manifest.get("package_status", "UNKNOWN")
            if _ms in ("READY_FOR_REVIEW", "READY_FOR_REVIEW_UNVERIFIED") and status_blockers:
                _ms = "BLOCKED_EVIDENCE"
            base_manifest["package_status"] = _ms
            base_manifest["ready_gate_matrix"] = gate_matrix
            base_manifest["snapshot_inventory_status"] = {
                "ok": not inventory_problems, "problems": inventory_problems[:8]}
            base_manifest["package_hash_chain"] = {
                "review_archive_plan_sha256": sha_plan,
                "review_zip_expectation_sha256": sha_expect,
                "review_subject_sha256": expect["review_subject_sha256"],
                "content_proof_sha256": expect["content_proof_sha256"],
                "commit_chain_sha256": commit_chain_sha,
                "commit_patchset_sha256": patchset_sha,
                "generated_artifacts": {"plan": plan_rel, "expectation": expect_rel,
                                        "manifest": manifest_rel},
            }
            manifest_bytes = (json.dumps(base_manifest, indent=2, sort_keys=True) + "\n").encode()

            generated = {plan_rel: (plan_bytes, 0o644), expect_rel: (expect_bytes, 0o644),
                         manifest_rel: (manifest_bytes, 0o644)}
            manifest_sha = _sha256_hex(manifest_bytes)
            gen_hashes = {plan_rel: sha_plan, expect_rel: sha_expect, manifest_rel: manifest_sha}

            # F6/F7 — the FINAL package status comes from the verified in-memory manifest bytes that
            # are packaged, captured HERE. The Shell uses these, never a post-build disk reread.
            _ce = base_manifest.get("current_evidence") or {}
            verified_status = {
                "package_status": base_manifest.get("package_status", "UNKNOWN"),
                "evidence_authoritative": bool(
                    _ce.get("evidence_freshness", {}).get("evidence_authoritative", False)),
                "review_subject_alignment": (base_manifest.get(
                    "review_subject_evidence_alignment", {}) or {}).get("verdict", "absent"),
                "manifest_sha256": manifest_sha,
            }

            # Persist the generated bytes next to the staged evidence for the exporter/other checks;
            # the ZIP is built from the in-memory bytes above, never these files.
            os.makedirs(base, exist_ok=True)
            for disk, data in ((args.plan_out, plan_bytes), (expect_disk, expect_bytes),
                               (args.manifest_disk, manifest_bytes)):
                with open(disk, "wb") as fh:
                    fh.write(data)
        else:
            # No evidence / no subject: the manifest is still a generated member, read no-follow.
            from packages.orchestration.review_zip import _read_manifest_no_follow
            manifest_bytes = _read_manifest_no_follow(args.manifest_disk)
            manifest_sha = _sha256_hex(manifest_bytes)
            generated = {args.manifest_rel: (manifest_bytes, 0o644)}
            gen_hashes = {args.manifest_rel: manifest_sha}
            # F5 (round 27): the NO_EVIDENCE manifest is trust-bearing (its package_status drives the
            # final status). Decode it strictly — a duplicate/ambiguous key BLOCKS, never a silent {}.
            _bm = _strict_loads(manifest_bytes, "no-evidence root manifest")
            if not isinstance(_bm, dict):
                raise ArchivePlanError("the no-evidence root manifest is not a JSON object")
            verified_status = {
                "package_status": _bm.get("package_status", "NO_EVIDENCE"),
                "evidence_authoritative": False,
                "review_subject_alignment": "absent",
                "manifest_sha256": manifest_sha,
            }

        # F1 (round 33/34) — the SINGLE publication. The coordinator already knows the verified
        # package_status from the in-memory manifest, so it derives the EXACT status-bearing final path
        # and publishes DIRECTLY to it. The ZIP is built into a PRIVATE same-directory `.part`, reopened
        # and verified there, its verified SHA-256 is bound, and that same inode is atomically linked
        # (no-replace) to the final path. There is NO public intermediate ZIP at any time: no pre-check-
        # then-write, no rename, no second publication. The atomic link is the race boundary, so exactly
        # one concurrent invocation wins and no existing destination is ever truncated.
        import tempfile as _tempfile

        from packages.orchestration.safe_publish import (
            CAPABILITY_SUPPORTED,
            PublishCollisionError,
            PublishSourceError,
            probe_anonymous_publication_capability,
            publish_atomically,
        )
        final_status = str(verified_status.get("package_status") or "UNKNOWN")
        final_path = _final_path_for(args.final_template, final_status)
        _out_dir = os.path.dirname(os.path.abspath(final_path)) or "."
        _pub_capability = probe_anonymous_publication_capability(_out_dir)
        if _pub_capability != CAPABILITY_SUPPORTED:
            print(f"REVIEW_ZIP_ERROR: anonymous publication not supported in "
                  f"{_out_dir!r}: {_pub_capability}", file=sys.stderr)
            print(json.dumps({"publication_capability": _pub_capability,
                              "publication_capability_directory": _out_dir,
                              **verified_status}))
            return 4
        _fd, _tmp = _tempfile.mkstemp(prefix=".remedy_zip_", suffix=".part", dir=_out_dir)
        os.close(_fd)
        published = False
        published_sha256 = ""
        try:
            result = build_review_zip_from_snapshot(
                out_path=_tmp, snapshot=snapshot, generated_members=generated)
            problems = verify_review_zip(_tmp, result)
            if problems:
                print("REVIEW_ZIP_VERIFICATION_FAILED:", file=sys.stderr)
                for p in problems:
                    print(f"  - {p}", file=sys.stderr)
                return 3
            # Bind the exact verified private bytes; publication refuses to publish anything else.
            published_sha256 = _sha256_hex(open(_tmp, "rb").read())
            try:
                publish_atomically(_tmp, final_path, args.repo_root,
                                   expected_sha256=published_sha256)
                published = True
            except (PublishCollisionError, PublishSourceError) as exc:
                print(f"REVIEW_ZIP_ERROR: {exc}", file=sys.stderr)
                return 3
        finally:
            if not published:
                try:
                    os.unlink(_tmp)                  # never leave a private partial artifact
                except OSError:
                    pass
    except (ReviewZipError, ArchivePlanError) as exc:
        print(f"REVIEW_ZIP_ERROR: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:                         # a ReviewSubjectError/ContentProofError/etc.
        print(f"REVIEW_ZIP_ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2

    authoritative = sum(1 for m in result["model"].values() if m.get("authoritative"))
    symlinks = sum(1 for m in result["model"].values() if m.get("kind") == "symlink")
    # F6/F7 — the reported status is the VERIFIED package model, not a disk-manifest reread.
    # F1 (round 34) — the coordinator returns the EXACT published final path and its verified SHA-256;
    # the shell trusts only these and never re-derives the name or re-publishes.
    print(json.dumps({"member_count": len(result["members"]),
                      "authoritative_count": authoritative,
                      "symlink_count": symlinks,
                      "tombstone_count": len(plan.tombstones),
                      "final_path": _reported_final_path(final_path, args.repo_root),
                      "final_sha256": published_sha256,
                      "publication_capability": _pub_capability,
                      **verified_status}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
