#!/usr/bin/env python3
"""Round 20 — the fail-closed, staged-source, directed-hash-chain ZIP construction stage.

Invoked by ``make_review_zip.sh`` AFTER Evidence has been safely staged. Everything it reads is a
staged byte (Subject, Content-Proof, Final-Verifier, Change-Provenance, Commit-Chain), never the
original ``EVIDENCE_DIR``. It:

* strict-decodes the ReviewSubject (fail-closed) and the ContentProofV1 authority (mandatory when a
  Subject is declared — no fail-open empty authority);
* proves the authority set EQUALS the Final-Verifier authoritative set, the Change-Provenance
  covered set, and the attestable Subject paths;
* builds ONE typed ArchivePlan, then SNAPSHOTS every source member's bytes once (anchored no-follow)
  so the bytes packaged and the bytes hashed are the same;
* fills every source member's expected hash into the CoreArchivePlan, then emits the directed chain
  ``review_archive_plan.json → review_zip_expectation.json → .review_zip_manifest.json`` as
  in-memory generated bytes (no artifact hashes itself, none is reopened by path);
* builds the deterministic ZIP from the immutable bytes and reopens it to verify the exact typed
  membership. Any block, escape, mismatch, or authority disagreement is a hard failure.
"""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from packages.orchestration.archive_plan import (  # noqa: E402
    ArchivePlanError,
    build_archive_plan,
)
from packages.orchestration.review_zip import (  # noqa: E402
    ReviewZipError,
    build_review_zip_from_snapshot,
    read_nul_list,
    snapshot_plan_members,
    verify_review_zip,
)


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _load_subject(path: str):
    """Fail closed. No path -> legacy empty subject. A supplied path that is missing, invalid JSON
    or schema-failing BLOCKS, never a silent downgrade to an empty subject (F10, round 19)."""
    from packages.orchestration.review_subject import (
        ReviewSubjectV1, decode_review_subject_from_json,
    )
    if not path:
        return ReviewSubjectV1(), b""
    if not os.path.isfile(path):
        raise ArchivePlanError(f"the declared review subject {path!r} is absent")
    try:
        raw = open(path, "rb").read()
        d = json.loads(raw)
    except (OSError, json.JSONDecodeError) as exc:
        raise ArchivePlanError(f"the declared review subject is not valid JSON: {exc}") from None
    return decode_review_subject_from_json(d), raw


def _load_content_proof(path: str, *, subject_declared: bool):
    """F2 (round 20): the ONE authority source, strict-decoded. When a Subject is declared the proof
    is MANDATORY; a missing/invalid/schema-failing proof BLOCKS. There is no fail-open ``set()``."""
    from packages.orchestration.review_subject import decode_content_proof_v1
    if not path or not os.path.isfile(path):
        if subject_declared:
            raise ArchivePlanError(
                "a ReviewSubject is declared but the Content Proof is absent — the authority set "
                "cannot be derived and the package is refused")
        return None, b""
    try:
        raw = open(path, "rb").read()
        d = json.loads(raw)
    except (OSError, json.JSONDecodeError) as exc:
        raise ArchivePlanError(f"the Content Proof is not valid JSON: {exc}") from None
    return decode_content_proof_v1(d), raw     # raises ContentProofError on schema failure


def _staged_json(evidence_root: str, rel: str):
    """Load one staged evidence JSON by relative path, or None if absent."""
    if not evidence_root:
        return None
    p = os.path.join(evidence_root, rel)
    if not os.path.isfile(p):
        return None
    try:
        return json.loads(open(p, "rb").read())
    except (OSError, json.JSONDecodeError) as exc:
        raise ArchivePlanError(f"staged {rel} is not valid JSON: {exc}") from None


def _prefix_paths(paths, prefix):
    return {f"{prefix}/{p}" for p in paths}


def _assert_authority_equality(*, authority: set, subject, content_proof, evidence_root: str,
                               current_prefix: str) -> None:
    """F2 (round 20): authority MUST equal every other authoritative set. Any disagreement blocks."""
    from packages.orchestration.repair_attest import is_attestable_source

    if content_proof is not None:
        if authority != content_proof.authority_paths():
            raise ArchivePlanError("authority set != Content-Proof file+tombstone paths")
        if subject.files:
            if content_proof.base_commit != subject.base_commit \
                    or content_proof.head_commit != subject.head_commit:
                raise ArchivePlanError("Content-Proof base/head != ReviewSubject base/head")

    attestable_subject = {f.path for f in subject.files if is_attestable_source(f.path)}
    if authority != attestable_subject:
        only_auth = sorted(authority - attestable_subject)[:4]
        only_subj = sorted(attestable_subject - authority)[:4]
        raise ArchivePlanError(
            f"authority set != attestable ReviewSubject paths "
            f"(only_in_authority={only_auth}, only_in_subject={only_subj})")

    fv = _staged_json(evidence_root, f"{current_prefix}/final_verifier_report.json")
    if fv is not None:
        fv_auth = set(fv.get("authoritative_changed_files") or [])
        if authority != fv_auth:
            raise ArchivePlanError("authority set != Final-Verifier authoritative_changed_files")
    cpg = _staged_json(evidence_root, f"{current_prefix}/change_provenance_gate.json")
    if cpg is not None:
        covered = set(cpg.get("covered_files") or [])
        if authority != covered:
            raise ArchivePlanError("authority set != Change-Provenance covered_files")


def _finalize_plan(plan, snapshot):
    """Fill every SOURCE member's expected content identity from the immutable snapshot, so the
    packaged CoreArchivePlan lets a ZIP-only reviewer recompute every source member's hash."""
    def _fill(members):
        out = []
        for m in members:
            snap = snapshot.get(m.archive_path)
            if snap is None:
                out.append(m)
                continue
            out.append(dataclasses.replace(
                m, expected_sha256=(None if snap.kind == "symlink" else snap.sha256),
                expected_link_target=(snap.link_target if snap.kind == "symlink" else None)))
        return tuple(out)
    return dataclasses.replace(plan, repository_members=_fill(plan.repository_members),
                               evidence_members=_fill(plan.evidence_members))


def _expected_model(snapshot, gen_hashes: dict) -> list:
    """The full expected member model (source + generated) a reviewer verifies, sorted by name."""
    rows = []
    for name in sorted(snapshot):
        m = snapshot[name]
        rows.append({"archive_path": name, "kind": m.kind, "mode": m.mode,
                     "sha256": m.sha256, "link_target": m.link_target,
                     "authoritative": m.authoritative})
    for name in sorted(gen_hashes):
        rows.append({"archive_path": name, "kind": "regular", "mode": 0o644,
                     "sha256": gen_hashes[name], "link_target": None, "authoritative": False})
    return sorted(rows, key=lambda r: r["archive_path"])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--repo-files0", required=True, help="NUL-delimited repo context file list")
    ap.add_argument("--evidence-root", default="", help="the STAGING root (single byte source)")
    ap.add_argument("--evidence-files0", default="", help="NUL-delimited staged evidence file list")
    ap.add_argument("--subject-json", default="", help="STAGED review_subject.json")
    ap.add_argument("--content-proof-json", default="", help="STAGED content proof (authority)")
    ap.add_argument("--current-prefix", default="evidence/current")
    ap.add_argument("--plan-out", default="", help="where to also write review_archive_plan.json")
    ap.add_argument("--manifest-rel", required=True)
    ap.add_argument("--manifest-disk", required=True)
    args = ap.parse_args()

    repo_files = read_nul_list(args.repo_files0)
    evidence_files = read_nul_list(args.evidence_files0) if args.evidence_files0 else []
    evidence_root = args.evidence_root or None

    try:
        subject, subject_bytes = _load_subject(args.subject_json)
        subject_declared = bool(subject.files)
        content_proof, proof_bytes = _load_content_proof(
            args.content_proof_json, subject_declared=subject_declared)
        authority = content_proof.authority_paths() if content_proof is not None else set()

        if subject_declared:
            _assert_authority_equality(
                authority=authority, subject=subject, content_proof=content_proof,
                evidence_root=args.evidence_root, current_prefix=args.current_prefix)

        plan = build_archive_plan(
            repo_root=args.repo_root, subject=subject, repo_context_rel=repo_files,
            evidence_root=evidence_root, evidence_rel=evidence_files,
            authoritative_paths=authority)

        # Phase 1 — snapshot every source member once (anchored no-follow, verified).
        snapshot = snapshot_plan_members(plan)

        generated: dict = {}
        gen_hashes: dict = {}
        if args.plan_out and evidence_root:
            base = os.path.dirname(args.plan_out)
            plan_rel = os.path.relpath(args.plan_out, evidence_root)
            expect_disk = os.path.join(base, "review_zip_expectation.json")
            expect_rel = os.path.relpath(expect_disk, evidence_root)
            manifest_rel = args.manifest_rel

            # Phase 2 — the CoreArchivePlan: every SOURCE member with its expected hash.
            finalized = _finalize_plan(plan, snapshot)
            plan_bytes = (json.dumps(finalized.to_json(), indent=2, sort_keys=True) + "\n").encode()
            sha_plan = _sha256_hex(plan_bytes)

            # Phase 3 — the expectation artifact carries plan_sha256 + the full expected model.
            expect = {
                "expectation_v": 1,
                "verifier": "review_zip.verify_review_zip/round20",
                "review_archive_plan_sha256": sha_plan,
                "review_subject_sha256": _sha256_hex(subject_bytes) if subject_bytes else "",
                "content_proof_sha256": _sha256_hex(proof_bytes) if proof_bytes else "",
                "authority_set_sha256": _sha256_hex(
                    json.dumps(sorted(authority)).encode()),
                "expected_member_count": len(snapshot) + 3,   # sources + plan + expectation + manifest
                "authoritative_member_count": sum(1 for m in snapshot.values() if m.authoritative),
                "symlink_member_count": sum(1 for m in snapshot.values() if m.kind == "symlink"),
                "tombstone_count": len(plan.tombstones),
                "generated_artifacts": sorted([plan_rel, expect_rel, manifest_rel]),
                "expected_members": _expected_model(snapshot, {}),
                "tombstones": [t.to_json() for t in plan.tombstones],
            }
            expect_bytes = (json.dumps(expect, indent=2, sort_keys=True) + "\n").encode()
            sha_expect = _sha256_hex(expect_bytes)

            # Phase 3 — the final manifest carries the whole directed chain of hashes.
            chain = _staged_json(evidence_root, f"{args.current_prefix}/review_commit_chain.json")
            commit_chain_sha = _sha256_hex(
                json.dumps(chain, sort_keys=True).encode()) if chain is not None else ""
            # The commit patch-set sha binds the staged commit patch bytes (by their snapshot hash).
            patch_ids = sorted(
                snapshot[name].sha256 for name in snapshot if "commit_patch" in name)
            patchset_sha = _sha256_hex(json.dumps(patch_ids).encode())

            from packages.orchestration.review_zip import _read_manifest_no_follow
            base_manifest = json.loads(_read_manifest_no_follow(args.manifest_disk))
            base_manifest["package_hash_chain"] = {
                "review_archive_plan_sha256": sha_plan,
                "review_zip_expectation_sha256": sha_expect,
                "review_subject_sha256": expect["review_subject_sha256"],
                "content_proof_sha256": expect["content_proof_sha256"],
                "commit_chain_sha256": commit_chain_sha,
                "commit_patchset_sha256": patchset_sha,
                "generated_artifacts": {"plan": plan_rel, "expectation": expect_rel,
                                        "manifest": manifest_rel},
            }
            manifest_bytes = (json.dumps(base_manifest, indent=2, sort_keys=True) + "\n").encode()

            generated = {plan_rel: (plan_bytes, 0o644), expect_rel: (expect_bytes, 0o644),
                         manifest_rel: (manifest_bytes, 0o644)}
            gen_hashes = {plan_rel: sha_plan, expect_rel: sha_expect,
                          manifest_rel: _sha256_hex(manifest_bytes)}

            # Persist the generated bytes next to the staged evidence for the exporter/other checks;
            # the ZIP is built from the in-memory bytes above, never these files.
            os.makedirs(base, exist_ok=True)
            for disk, data in ((args.plan_out, plan_bytes), (expect_disk, expect_bytes),
                               (args.manifest_disk, manifest_bytes)):
                with open(disk, "wb") as fh:
                    fh.write(data)
        else:
            # No evidence / no subject: the manifest is still a generated member, read no-follow.
            from packages.orchestration.review_zip import _read_manifest_no_follow
            manifest_bytes = _read_manifest_no_follow(args.manifest_disk)
            generated = {args.manifest_rel: (manifest_bytes, 0o644)}
            gen_hashes = {args.manifest_rel: _sha256_hex(manifest_bytes)}

        # Phase 4 — build the deterministic ZIP from immutable bytes; Phase 5 — reopen and verify.
        result = build_review_zip_from_snapshot(
            out_path=args.out, snapshot=snapshot, generated_members=generated)
        problems = verify_review_zip(args.out, result)
    except (ReviewZipError, ArchivePlanError) as exc:
        print(f"REVIEW_ZIP_ERROR: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:                         # a ReviewSubjectError/ContentProofError/etc.
        print(f"REVIEW_ZIP_ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2

    if problems:
        print("REVIEW_ZIP_VERIFICATION_FAILED:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        try:
            os.unlink(args.out)                      # F10: retain the output only when clean
        except OSError:
            pass
        return 3

    authoritative = sum(1 for m in result["model"].values() if m.get("authoritative"))
    symlinks = sum(1 for m in result["model"].values() if m.get("kind") == "symlink")
    print(json.dumps({"member_count": len(result["members"]),
                      "authoritative_count": authoritative,
                      "symlink_count": symlinks,
                      "tombstone_count": len(plan.tombstones)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
