#!/usr/bin/env python3
"""Round 20 — the fail-closed, staged-source, directed-hash-chain ZIP construction stage.

Invoked by ``make_review_zip.sh`` AFTER Evidence has been safely staged. Everything it reads is a
staged byte (Subject, Content-Proof, Final-Verifier, Change-Provenance, Commit-Chain), never the
original ``EVIDENCE_DIR``. It:

* strict-decodes the ReviewSubject (fail-closed) and the ContentProofV1 authority (mandatory when a
  Subject is declared — no fail-open empty authority);
* proves the authority set EQUALS the Final-Verifier authoritative set, the Change-Provenance
  covered set, and the attestable Subject paths;
* builds ONE typed ArchivePlan, then SNAPSHOTS every source member's bytes once (anchored no-follow)
  so the bytes packaged and the bytes hashed are the same;
* fills every source member's expected hash into the CoreArchivePlan, then emits the directed chain
  ``review_archive_plan.json → review_zip_expectation.json → .review_zip_manifest.json`` as
  in-memory generated bytes (no artifact hashes itself, none is reopened by path);
* builds the deterministic ZIP from the immutable bytes and reopens it to verify the exact typed
  membership. Any block, escape, mismatch, or authority disagreement is a hard failure.
"""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from packages.orchestration.archive_plan import (  # noqa: E402
    ArchivePlanError,
    build_archive_plan,
)
from packages.orchestration.review_zip import (  # noqa: E402
    ReviewZipError,
    build_review_zip_from_snapshot,
    read_nul_list,
    snapshot_plan_members,
    verify_review_zip,
)


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


class _StagedArtifacts:
    """F5 (round 21): the ONE immutable staged byte map. Each root artifact is read from the staging
    snapshot EXACTLY ONCE; objects are decoded from these bytes and the Plan's evidence members carry
    these exact shas, so `snapshot_plan_members` refuses if a staged file changed between decode and
    package — decode-bytes and package-bytes are provably identical."""

    def __init__(self, evidence_root: str | None, current_prefix: str):
        self.by_arcname: dict[str, tuple[bytes, str]] = {}     # arcname -> (bytes, sha256)
        self._root = evidence_root
        self._prefix = current_prefix

    def load(self, name: str) -> tuple[bytes | None, str]:
        """Read `<prefix>/<name>` once (bytes, sha). Absent -> (None, "")."""
        if not self._root:
            return None, ""
        arc = f"{self._prefix}/{name}"
        if arc in self.by_arcname:
            return self.by_arcname[arc]
        p = os.path.join(self._root, arc)
        if not os.path.isfile(p):
            return None, ""
        raw = open(p, "rb").read()
        rec = (raw, _sha256_hex(raw))
        self.by_arcname[arc] = rec
        return rec

    def load_json(self, name: str):
        raw, _ = self.load(name)
        if raw is None:
            return None
        try:
            return json.loads(raw)
        except json.JSONDecodeError as exc:
            raise ArchivePlanError(f"staged {name} is not valid JSON: {exc}") from None


def _decode_subject(raw: bytes | None):
    """Fail closed. No bytes -> legacy empty subject. Invalid JSON or schema failure BLOCKS."""
    from packages.orchestration.review_subject import (
        ReviewSubjectV1, decode_review_subject_from_json,
    )
    if raw is None:
        return ReviewSubjectV1()
    try:
        d = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ArchivePlanError(f"the declared review subject is not valid JSON: {exc}") from None
    return decode_review_subject_from_json(d)


def _decode_content_proof(raw: bytes | None, *, subject_declared: bool):
    """F2/F3 (round 20/21): the ONE authority source, strict-decoded. When a Subject is DECLARED the
    proof is MANDATORY (even with zero files); a missing/invalid/schema-failing proof BLOCKS."""
    from packages.orchestration.review_subject import decode_content_proof_v1
    if raw is None:
        if subject_declared:
            raise ArchivePlanError(
                "a ReviewSubject is declared but the Content Proof is absent — the authority set "
                "cannot be derived and the package is refused")
        return None
    try:
        d = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ArchivePlanError(f"the Content Proof is not valid JSON: {exc}") from None
    return decode_content_proof_v1(d)     # raises ContentProofError on schema failure


def _assert_authority_equality(*, authority: set, subject, content_proof, staged) -> None:
    """F2 (round 20): authority MUST equal every other authoritative set — all decoded from the ONE
    staged byte map (F5). Any disagreement blocks."""
    from packages.orchestration.repair_attest import is_attestable_source

    if content_proof is not None:
        if authority != content_proof.authority_paths():
            raise ArchivePlanError("authority set != Content-Proof file+tombstone paths")
        if content_proof.base_commit != subject.base_commit \
                or content_proof.head_commit != subject.head_commit:
            raise ArchivePlanError("Content-Proof base/head != ReviewSubject base/head")

    attestable_subject = {f.path for f in subject.files if is_attestable_source(f.path)}
    if authority != attestable_subject:
        only_auth = sorted(authority - attestable_subject)[:4]
        only_subj = sorted(attestable_subject - authority)[:4]
        raise ArchivePlanError(
            f"authority set != attestable ReviewSubject paths "
            f"(only_in_authority={only_auth}, only_in_subject={only_subj})")

    fv = staged.load_json("final_verifier_report.json")
    if fv is not None:
        if authority != set(fv.get("authoritative_changed_files") or []):
            raise ArchivePlanError("authority set != Final-Verifier authoritative_changed_files")
    cpg = staged.load_json("change_provenance_gate.json")
    if cpg is not None:
        if authority != set(cpg.get("covered_files") or []):
            raise ArchivePlanError("authority set != Change-Provenance covered_files")


def _bind_staged_expected_hashes(plan, by_arcname: dict):
    """F5: set each pre-read staged artifact's decode-time sha as its plan evidence member's expected
    hash, so the snapshot read that packages it must reproduce the exact bytes that were decoded."""
    def _fill(members):
        out = []
        for m in members:
            rec = by_arcname.get(m.archive_path)
            if rec is not None and m.kind == "regular":
                out.append(dataclasses.replace(m, expected_sha256=rec[1]))
            else:
                out.append(m)
        return tuple(out)
    return dataclasses.replace(plan, evidence_members=_fill(plan.evidence_members))


def _finalize_plan(plan, snapshot):
    """Fill every SOURCE member's expected content identity from the immutable snapshot, so the
    packaged CoreArchivePlan lets a ZIP-only reviewer recompute every source member's hash."""
    def _fill(members):
        out = []
        for m in members:
            snap = snapshot.get(m.archive_path)
            if snap is None:
                out.append(m)
                continue
            out.append(dataclasses.replace(
                m, expected_sha256=(None if snap.kind == "symlink" else snap.sha256),
                expected_link_target=(snap.link_target if snap.kind == "symlink" else None)))
        return tuple(out)
    return dataclasses.replace(plan, repository_members=_fill(plan.repository_members),
                               evidence_members=_fill(plan.evidence_members))


def _expected_model(snapshot, gen_hashes: dict) -> list:
    """The full expected member model (source + generated) a reviewer verifies, sorted by name."""
    rows = []
    for name in sorted(snapshot):
        m = snapshot[name]
        rows.append({"archive_path": name, "kind": m.kind, "mode": m.mode,
                     "sha256": m.sha256, "link_target": m.link_target,
                     "authoritative": m.authoritative})
    for name in sorted(gen_hashes):
        rows.append({"archive_path": name, "kind": "regular", "mode": 0o644,
                     "sha256": gen_hashes[name], "link_target": None, "authoritative": False})
    return sorted(rows, key=lambda r: r["archive_path"])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--repo-files0", required=True, help="NUL-delimited repo context file list")
    ap.add_argument("--evidence-root", default="", help="the STAGING root (single byte source)")
    ap.add_argument("--evidence-files0", default="", help="NUL-delimited staged evidence file list")
    ap.add_argument("--subject-json", default="", help="STAGED review_subject.json")
    ap.add_argument("--content-proof-json", default="", help="STAGED content proof (authority)")
    ap.add_argument("--current-prefix", default="evidence/current")
    ap.add_argument("--plan-out", default="", help="where to also write review_archive_plan.json")
    ap.add_argument("--manifest-rel", required=True)
    ap.add_argument("--manifest-disk", required=True)
    args = ap.parse_args()

    repo_files = read_nul_list(args.repo_files0)
    evidence_files = read_nul_list(args.evidence_files0) if args.evidence_files0 else []
    evidence_root = args.evidence_root or None

    try:
        # F5 — read the root artifacts from the ONE immutable staged byte map (once each).
        staged = _StagedArtifacts(evidence_root, args.current_prefix)
        subject_bytes, subject_sha = staged.load("review_subject.json")
        proof_bytes, proof_sha = staged.load("current_change_content_proof.json")
        _, chain_sha = staged.load("review_commit_chain.json")

        subject = _decode_subject(subject_bytes)
        # F3 — a Subject is declared by its base declaration, not by having files; a declared
        # zero-file / net-zero / revert subject still requires a strict Proof.
        subject_declared = subject.declared
        content_proof = _decode_content_proof(proof_bytes, subject_declared=subject_declared)
        authority = content_proof.authority_paths() if content_proof is not None else set()

        if subject_declared:
            _assert_authority_equality(authority=authority, subject=subject,
                                       content_proof=content_proof, staged=staged)

        # F2 — the plan's subject identity is the RAW packaged Subject bytes' sha256.
        plan = build_archive_plan(
            repo_root=args.repo_root, subject=subject, repo_context_rel=repo_files,
            evidence_root=evidence_root, evidence_rel=evidence_files,
            authoritative_paths=authority,
            review_subject_raw_sha256=(subject_sha or None))

        # F5 — bind every pre-read staged artifact's decode-time sha into its plan evidence member,
        # so snapshot_plan_members REFUSES if the staged file changed between decode and package.
        plan = _bind_staged_expected_hashes(plan, staged.by_arcname)

        # Phase 1 — snapshot every source member once (anchored no-follow, verified).
        snapshot = snapshot_plan_members(plan)

        generated: dict = {}
        gen_hashes: dict = {}
        verified_status = {"package_status": "NO_EVIDENCE", "evidence_authoritative": False,
                           "review_subject_alignment": "absent", "manifest_sha256": ""}
        if args.plan_out and evidence_root:
            base = os.path.dirname(args.plan_out)
            plan_rel = os.path.relpath(args.plan_out, evidence_root)
            expect_disk = os.path.join(base, "review_zip_expectation.json")
            expect_rel = os.path.relpath(expect_disk, evidence_root)
            manifest_rel = args.manifest_rel

            # Phase 2 — the CoreArchivePlan: every SOURCE member with its expected hash.
            finalized = _finalize_plan(plan, snapshot)
            plan_bytes = (json.dumps(finalized.to_json(), indent=2, sort_keys=True) + "\n").encode()
            sha_plan = _sha256_hex(plan_bytes)

            # Phase 3 — the expectation artifact carries plan_sha256 + the full expected model.
            # F2 — every *_sha256 here is the RAW packaged bytes' sha (subject/proof from the one
            # staged byte map), never a reserialized projection.
            expect = {
                "expectation_v": 1,
                "verifier": "review_zip.verify_review_zip/round21",
                "review_archive_plan_sha256": sha_plan,
                "review_subject_sha256": subject_sha,
                "content_proof_sha256": proof_sha,
                "authority_set_sha256": _sha256_hex(
                    json.dumps(sorted(authority)).encode()),
                "expected_member_count": len(snapshot) + 3,   # sources + plan + expectation + manifest
                "authoritative_member_count": sum(1 for m in snapshot.values() if m.authoritative),
                "symlink_member_count": sum(1 for m in snapshot.values() if m.kind == "symlink"),
                "tombstone_count": len(plan.tombstones),
                "generated_artifacts": sorted([plan_rel, expect_rel, manifest_rel]),
                "expected_members": _expected_model(snapshot, {}),
                "tombstones": [t.to_json() for t in plan.tombstones],
            }
            expect_bytes = (json.dumps(expect, indent=2, sort_keys=True) + "\n").encode()
            sha_expect = _sha256_hex(expect_bytes)

            # F4 — the commit-chain sha is the RAW packaged bytes' sha, from the staged map.
            commit_chain_sha = chain_sha
            # The commit patch-set sha binds the staged commit patch bytes (by their snapshot hash).
            patch_ids = sorted(
                snapshot[name].sha256 for name in snapshot if "commit_patch" in name)
            patchset_sha = _sha256_hex(json.dumps(patch_ids).encode())

            from packages.orchestration.review_zip import _read_manifest_no_follow
            base_manifest = json.loads(_read_manifest_no_follow(args.manifest_disk))
            base_manifest["package_hash_chain"] = {
                "review_archive_plan_sha256": sha_plan,
                "review_zip_expectation_sha256": sha_expect,
                "review_subject_sha256": expect["review_subject_sha256"],
                "content_proof_sha256": expect["content_proof_sha256"],
                "commit_chain_sha256": commit_chain_sha,
                "commit_patchset_sha256": patchset_sha,
                "generated_artifacts": {"plan": plan_rel, "expectation": expect_rel,
                                        "manifest": manifest_rel},
            }
            manifest_bytes = (json.dumps(base_manifest, indent=2, sort_keys=True) + "\n").encode()

            generated = {plan_rel: (plan_bytes, 0o644), expect_rel: (expect_bytes, 0o644),
                         manifest_rel: (manifest_bytes, 0o644)}
            manifest_sha = _sha256_hex(manifest_bytes)
            gen_hashes = {plan_rel: sha_plan, expect_rel: sha_expect, manifest_rel: manifest_sha}

            # F6/F7 — the FINAL package status comes from the verified in-memory manifest bytes that
            # are packaged, captured HERE. The Shell uses these, never a post-build disk reread.
            _ce = base_manifest.get("current_evidence") or {}
            verified_status = {
                "package_status": base_manifest.get("package_status", "UNKNOWN"),
                "evidence_authoritative": bool(
                    _ce.get("evidence_freshness", {}).get("evidence_authoritative", False)),
                "review_subject_alignment": (base_manifest.get(
                    "review_subject_evidence_alignment", {}) or {}).get("verdict", "absent"),
                "manifest_sha256": manifest_sha,
            }

            # Persist the generated bytes next to the staged evidence for the exporter/other checks;
            # the ZIP is built from the in-memory bytes above, never these files.
            os.makedirs(base, exist_ok=True)
            for disk, data in ((args.plan_out, plan_bytes), (expect_disk, expect_bytes),
                               (args.manifest_disk, manifest_bytes)):
                with open(disk, "wb") as fh:
                    fh.write(data)
        else:
            # No evidence / no subject: the manifest is still a generated member, read no-follow.
            from packages.orchestration.review_zip import _read_manifest_no_follow
            manifest_bytes = _read_manifest_no_follow(args.manifest_disk)
            manifest_sha = _sha256_hex(manifest_bytes)
            generated = {args.manifest_rel: (manifest_bytes, 0o644)}
            gen_hashes = {args.manifest_rel: manifest_sha}
            try:
                _bm = json.loads(manifest_bytes)
            except json.JSONDecodeError:
                _bm = {}
            verified_status = {
                "package_status": _bm.get("package_status", "NO_EVIDENCE"),
                "evidence_authoritative": False,
                "review_subject_alignment": "absent",
                "manifest_sha256": manifest_sha,
            }

        # Phase 4 — build the deterministic ZIP from immutable bytes; Phase 5 — reopen and verify.
        result = build_review_zip_from_snapshot(
            out_path=args.out, snapshot=snapshot, generated_members=generated)
        problems = verify_review_zip(args.out, result)
    except (ReviewZipError, ArchivePlanError) as exc:
        print(f"REVIEW_ZIP_ERROR: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:                         # a ReviewSubjectError/ContentProofError/etc.
        print(f"REVIEW_ZIP_ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2

    if problems:
        print("REVIEW_ZIP_VERIFICATION_FAILED:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        try:
            os.unlink(args.out)                      # F10: retain the output only when clean
        except OSError:
            pass
        return 3

    authoritative = sum(1 for m in result["model"].values() if m.get("authoritative"))
    symlinks = sum(1 for m in result["model"].values() if m.get("kind") == "symlink")
    # F6/F7 — the reported status is the VERIFIED package model, not a disk-manifest reread.
    print(json.dumps({"member_count": len(result["members"]),
                      "authoritative_count": authoritative,
                      "symlink_count": symlinks,
                      "tombstone_count": len(plan.tombstones),
                      **verified_status}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
