#!/usr/bin/env bash
# remedy_smoke.sh — Project Registry + Brain Viewer smoke test.
#
# Usage (source):
#   source scripts/remedy_smoke.sh
#   remedy_smoke
#
# Usage (direct):
#   ./scripts/remedy_smoke.sh
#
# Requirements: remedy CLI on PATH, python3.
# Optional: Ollama running locally (for run-next-task-local).
#
# Overrides:
#   REMEDY_SMOKE_REPO  — temp repo path (default: /tmp/remedy-target-repo)
#
# TARGET_REPO is recreated fresh on each run (rm -rf + mkdir).  The whole-repo
# markerless scan (step 7g) is therefore a developer smoke invariant that proves
# Remedy's own writes contain no raw "<!--" HTML comments or "Generated by Remedy"
# provenance strings.  It is not a runtime policy for arbitrary user repos.

remedy_smoke() {
  (
    set -euo pipefail

    local TARGET_REPO="${REMEDY_SMOKE_REPO:-/tmp/remedy-target-repo}"
    local PROMPT="${1:-Create exactly one task with task_type write_readme: Write a README for a small internal CLI tool. No further tasks.}"

    # Resolve run-log root: $REMEDY_DATA_DIR/runs or .data/runs (public filesystem convention)
    local RUNS_ROOT
    if [[ -n "${REMEDY_DATA_DIR:-}" ]]; then
        RUNS_ROOT="${REMEDY_DATA_DIR}/runs"
    else
        RUNS_ROOT=".data/runs"
    fi

    # -------------------------------------------------------------------------
    # 1. Create target repo
    # -------------------------------------------------------------------------
    echo "--- 1. Create target repo: ${TARGET_REPO}"
    rm -rf "${TARGET_REPO}"
    mkdir -p "${TARGET_REPO}"
    cat >"${TARGET_REPO}/AGENTS.md" <<'AGENTS_EOF'
# Test Target Repo
AGENTS_EOF
    cat >"${TARGET_REPO}/pyproject.toml" <<'PYPROJECT_EOF'
[project]
name = "smoke-target"
version = "0.1.0"
PYPROJECT_EOF
    # Seed README.md so modify-action apply always finds the target file.
    # v0 patch apply only supports modify on existing files; create on new files.
    # The write_readme task produces a modify intent targeting README.md.
    cat >"${TARGET_REPO}/README.md" <<'README_EOF'
# Tiny Internal Tool

Initial README content.
README_EOF

    # -------------------------------------------------------------------------
    # 2. Create project
    # -------------------------------------------------------------------------
    echo "--- 2. Create project"
    PROJECT_ID="$(remedy create-project "Smoke Project" --description "smoke test project")"
    if [[ -z "${PROJECT_ID}" ]]; then
        echo "ERROR: create-project did not print a project ID" >&2
        return 1
    fi
    echo "    PROJECT_ID=${PROJECT_ID}"

    # -------------------------------------------------------------------------
    # 3. Create job (linked to project, explicit task_type — no plan-job needed)
    # -------------------------------------------------------------------------
    echo "--- 3. Create job"
    JOB_ID="$(remedy create-job "${PROMPT}" \
        --project "${PROJECT_ID}" \
        --task-type write_readme \
        --task-description "Write/update README.md for smoke target.")"
    if [[ -z "${JOB_ID}" ]]; then
        echo "ERROR: create-job did not print a job ID" >&2
        return 1
    fi
    echo "    JOB_ID=${JOB_ID}"

    # Assert: job starts in PLANNED state with exactly one write_readme task.
    # Pipe show-job output to a temp file so Python can parse it without
    # calling remedy again via a nested subprocess from within the script.
    _TMP_JOB="$(mktemp)"
    remedy show-job "${JOB_ID}" > "${_TMP_JOB}"
    python3 -c "
import json, sys
from pathlib import Path
job = json.loads(Path(sys.argv[1]).read_text())
state = job.get('state', '')
tasks = job.get('tasks', [])
if state != 'planned':
    print('ERROR: job state must be planned after create-job --task-type, got: ' + repr(state), file=sys.stderr)
    sys.exit(1)
if len(tasks) != 1:
    print('ERROR: expected exactly 1 task, got ' + str(len(tasks)), file=sys.stderr)
    sys.exit(1)
tt = tasks[0].get('inputs', {}).get('task_type', '')
if tt != 'write_readme':
    print('ERROR: task task_type must be write_readme, got: ' + repr(tt), file=sys.stderr)
    sys.exit(1)
print('    job state=planned, 1 task, task_type=write_readme: OK')
" "${_TMP_JOB}"
    rm -f "${_TMP_JOB}"

    # -------------------------------------------------------------------------
    # 4. Attach repo + set permission; link repo to project
    # -------------------------------------------------------------------------
    echo "--- 4. Attach repo + set permission"
    remedy attach-repo "${JOB_ID}" "${TARGET_REPO}"
    remedy set-permission "${JOB_ID}" allow repo_generated_write
    remedy attach-project-repo "${PROJECT_ID}" "${TARGET_REPO}"

    # -------------------------------------------------------------------------
    # 5. Run next task (requires Ollama — skip gracefully if unavailable)
    # -------------------------------------------------------------------------
    echo "--- 5. run-next-task-local"
    if remedy run-next-task-local "${JOB_ID}"; then
        echo "    Task run: OK"
    else
        echo "    Task run: SKIP (Ollama likely unavailable — continuing smoke)"
    fi

    # -------------------------------------------------------------------------
    # 6. Patch apply lifecycle: before approval → approve → apply → noop
    # -------------------------------------------------------------------------
    echo "--- 6. Patch apply lifecycle (if intent present)"
    FIRST_INTENT_ID="$(remedy brain "${JOB_ID}" --json | python3 -c "
import json,sys
data=json.load(sys.stdin)
for n in data.get('nodes', []):
    if n.get('type') == 'patch_intent':
        nid = n['id']
        print(nid[3:] if nid.startswith('pi:') else nid)
        break
" 2>/dev/null || true)"
    if [[ -n "${FIRST_INTENT_ID}" ]]; then
        # 6a. apply before approval must be blocked (non-zero exit)
        echo "--- 6a. Apply before approval (expect blocked)"
        if remedy apply-patch-intent "${JOB_ID}" "${FIRST_INTENT_ID}" 2>/dev/null; then
            echo "ERROR: apply-patch-intent should fail before approval" >&2
            return 1
        fi
        echo "    apply before approval: blocked (OK)"

        # 6b. approve
        echo "--- 6b. Approve patch intent"
        remedy approve-patch-intent "${JOB_ID}" "${FIRST_INTENT_ID}" --reason "smoke approval"
        echo "    Approved: ${FIRST_INTENT_ID}"

        # 6c. apply approved intent (must succeed)
        echo "--- 6c. Apply approved patch intent"
        remedy apply-patch-intent "${JOB_ID}" "${FIRST_INTENT_ID}"
        echo "    Applied: ${FIRST_INTENT_ID} (OK)"

        # 6d. repeat apply (must be no-op, exit 0)
        echo "--- 6d. Repeat apply (no-op)"
        remedy apply-patch-intent "${JOB_ID}" "${FIRST_INTENT_ID}"
        echo "    Repeat apply: no-op (OK)"

        # 6e. verify applied file has no Remedy control markers
        echo "--- 6e. Verify applied file has no Remedy control markers"
        APPLIED_TARGET="$(remedy brain "${JOB_ID}" --json | python3 -c "
import json, sys
data = json.load(sys.stdin)
for n in data.get('nodes', []):
    if n.get('type') == 'patch_apply':
        print(n.get('metadata', {}).get('target_path', ''))
        break
" 2>/dev/null || true)"
        if [[ -z "${APPLIED_TARGET}" ]]; then
            echo "ERROR: patch_apply node target_path missing from brain after apply lifecycle" >&2
            return 1
        fi
        python3 -c "
import sys
from pathlib import Path
target_file = Path(sys.argv[1]) / sys.argv[2]
intent_id   = sys.argv[3]
if not target_file.exists():
    print('ERROR: applied file ' + str(target_file) + ' does not exist after apply', file=sys.stderr)
    sys.exit(1)
content = target_file.read_text()
bad = [
    ('<!--',               'raw HTML comment start'),
    ('Generated by Remedy','Remedy provenance string'),
]
failed = []
for needle, desc in bad:
    if needle in content:
        failed.append(f'FOUND {desc!r}: {needle!r}')
if intent_id and intent_id in content:
    failed.append('FOUND intent_id in file content')
if failed:
    for msg in failed:
        print('ERROR: ' + msg, file=sys.stderr)
    sys.exit(1)
if '## Proposed Update' not in content:
    print('ERROR: ## Proposed Update section missing from applied file', file=sys.stderr)
    sys.exit(1)
if not content.endswith('\n'):
    print('ERROR: applied file does not end with a newline', file=sys.stderr)
    sys.exit(1)
print('    Applied file: OK (no raw HTML comments, has Proposed Update section, ends with newline)')
" "${TARGET_REPO}" "${APPLIED_TARGET}" "${FIRST_INTENT_ID}"

        # 6f. verify exact run-log schema for patch_intent_applied events
        echo "--- 6f. Verify run-log schema (patch_intent_applied)"
        python3 -c "
import json, sys
from pathlib import Path
job_id   = sys.argv[1]
runs_dir = Path(sys.argv[2]) / job_id
events   = []
if runs_dir.exists():
    for f in sorted(runs_dir.glob('*.jsonl')):
        for line in f.read_text().splitlines():
            if line.strip():
                ev = json.loads(line)
                if ev.get('event') == 'patch_intent_applied':
                    events.append(ev)
if not events:
    print('ERROR: no patch_intent_applied events found in ' + str(runs_dir), file=sys.stderr)
    sys.exit(1)
required_meta = frozenset({'intent_id','target_path','action','outcome','bytes_written','line_count'})
bad_keys      = frozenset({'approval_reason','diff_preview','command_output','content','traceback'})
bad_strs      = ['Traceback', 'Exception:']
outcomes      = {e['metadata'].get('outcome') for e in events}
for ev in events:
    meta = ev.get('metadata', {})
    got  = frozenset(meta.keys())
    if got != required_meta:
        print('ERROR: metadata keys mismatch: got=' + str(sorted(got)) + ' want=' + str(sorted(required_meta)), file=sys.stderr)
        sys.exit(1)
    if got & bad_keys:
        print('ERROR: forbidden metadata keys: ' + str(sorted(got & bad_keys)), file=sys.stderr)
        sys.exit(1)
    ev_str = json.dumps(ev)
    for s in bad_strs:
        if s in ev_str:
            print('ERROR: forbidden substring ' + repr(s) + ' in event', file=sys.stderr)
            sys.exit(1)
for need in ('blocked', 'applied', 'noop'):
    if need not in outcomes:
        print('ERROR: expected outcome=' + need + ' not found in events; got=' + str(sorted(outcomes)), file=sys.stderr)
        sys.exit(1)
print('    run-log schema: OK  events=' + str(len(events)) + '  outcomes=' + str(sorted(outcomes)))
" "${JOB_ID}" "${RUNS_ROOT}"
        # 6g. whole-TARGET_REPO markerless scan
        echo "--- 6g. Whole-repo markerless scan"
        python3 -c "
from pathlib import Path
import sys
root       = Path(sys.argv[1])
intent_id  = sys.argv[2]
needles    = ['Generated by Remedy', '<!--']
if intent_id:
    needles.append(intent_id)
bad = []
for p in root.rglob('*'):
    if not p.is_file():
        continue
    try:
        text = p.read_text(encoding='utf-8')
    except (UnicodeDecodeError, OSError):
        continue
    for needle in needles:
        if needle in text:
            bad.append((str(p), needle))
if bad:
    for path, needle in bad:
        print('ERROR: ' + path + ' contains forbidden marker/provenance ' + repr(needle), file=sys.stderr)
    sys.exit(1)
print('    target repo markerless: OK')
" "${TARGET_REPO}" "${FIRST_INTENT_ID}"
    else
        echo "    No patch intents found — skipping apply lifecycle"
    fi

    # -------------------------------------------------------------------------
    # 7. Assert: remedy project --json (alias)
    # -------------------------------------------------------------------------
    echo "--- 7. Assert: remedy project --json"
    PROJECT_JSON="$(remedy project "${PROJECT_ID}" --json)"
    python3 -c "
import json,sys
data=json.loads(sys.argv[1])
assert data['version'] == 1, f'version must be 1, got {data[\"version\"]}'
assert data['project']['id'] == sys.argv[2], 'project id mismatch'
jobs = data.get('jobs', [])
assert any(j['id'] == sys.argv[3] for j in jobs), f'job {sys.argv[3][:8]} not in project jobs'
print(f'    remedy project --json: OK (version={data[\"version\"]}, jobs={len(jobs)})')
" "${PROJECT_JSON}" "${PROJECT_ID}" "${JOB_ID}"

    # -------------------------------------------------------------------------
    # 8. Assert: remedy show-project --json (backward compat)
    # -------------------------------------------------------------------------
    echo "--- 8. Assert: remedy show-project --json"
    SHOW_JSON="$(remedy show-project "${PROJECT_ID}" --json)"
    python3 -c "
import json,sys
data=json.loads(sys.argv[1])
assert data['version'] == 1, 'show-project version must be 1'
print('    remedy show-project --json: OK')
" "${SHOW_JSON}"

    # -------------------------------------------------------------------------
    # 9. Assert: context score 0..85
    # -------------------------------------------------------------------------
    echo "--- 9. Assert context score"
    CTX_SCORE="$(remedy context "${JOB_ID}" --json | python3 -c "
import json,sys
data=json.load(sys.stdin)
print(data['score'])
")"
    if [[ "${CTX_SCORE}" -lt 0 ]] || [[ "${CTX_SCORE}" -gt 85 ]]; then
        echo "ERROR: context score ${CTX_SCORE} is outside 0..85" >&2
        return 1
    fi
    echo "    Context score: ${CTX_SCORE} (OK)"

    # -------------------------------------------------------------------------
    # 10. Assert: brain JSON has required node types + project_placeholder
    # -------------------------------------------------------------------------
    echo "--- 10. Assert brain node types (including project_placeholder)"
    remedy brain "${JOB_ID}" --json | python3 -c "
import json,sys
data=json.load(sys.stdin)
types={n['type'] for n in data.get('nodes', [])}
first_intent_id=sys.argv[1]
core=['job','task','context_coverage']
missing_core=[t for t in core if t not in types]
if missing_core:
    print('ERROR: brain missing core node types: '+', '.join(missing_core), file=sys.stderr)
    sys.exit(1)
if 'project_placeholder' not in types:
    print('ERROR: project_placeholder node missing from brain', file=sys.stderr)
    sys.exit(1)
if first_intent_id and 'patch_apply' not in types:
    print('ERROR: patch_apply node missing after apply lifecycle completed', file=sys.stderr)
    sys.exit(1)
print('    Brain types: '+', '.join(sorted(types)))
" "${FIRST_INTENT_ID}"

    # -------------------------------------------------------------------------
    # 11. Generate Brain Viewer
    # -------------------------------------------------------------------------
    echo "--- 11. remedy brain-view"
    BRAIN_VIEW_OUTPUT="$(remedy brain-view "${JOB_ID}")" || {
        echo "ERROR: brain-view failed" >&2
        return 1
    }
    VIEW_PATH="$(printf '%s\n' "${BRAIN_VIEW_OUTPUT}" \
        | awk '/^Brain Viewer v0:/ {sub(/^Brain Viewer v0: /, ""); print; exit}' || true)"
    if [[ -z "${VIEW_PATH}" ]]; then
        echo "ERROR: brain-view did not print a 'Brain Viewer v0:' line" >&2
        printf "Output was:\n%s\n" "${BRAIN_VIEW_OUTPUT}" >&2
        return 1
    fi
    VIEW_DIR="$(dirname "${VIEW_PATH}")"

    # -------------------------------------------------------------------------
    # 12. Assert viewer files (self-diagnosing — no bare assert)
    # -------------------------------------------------------------------------
    echo "--- 12. Assert viewer files"
    python3 -c "
import json, sys
from pathlib import Path

view_dir  = Path(sys.argv[1])
vd_path   = view_dir / 'viewer_data.json'
html_path = view_dir / 'index.html'
failed    = []

# --- viewer_data.json ---
if not vd_path.exists():
    print('ERROR: viewer sanity failed: ' + str(vd_path) + ' does not exist', file=sys.stderr)
    sys.exit(1)
try:
    data = json.loads(vd_path.read_text())
except Exception as exc:
    print('ERROR: viewer sanity failed: ' + str(vd_path) + ' is not valid JSON: ' + str(exc), file=sys.stderr)
    sys.exit(1)

if data.get('version') != 1:
    failed.append('viewer_data.json version=' + repr(data.get('version')) + ' (want 1)')
for key in ('graph', 'node_details', 'positions', 'detail_fallback_count'):
    if key not in data:
        failed.append('viewer_data.json missing key: ' + repr(key))
nodes = data.get('graph', {}).get('nodes', [])
if not nodes:
    failed.append('viewer_data.json graph.nodes is empty')
nd = data.get('node_details', {})
if len(nd) != len(nodes):
    failed.append('node_details count=' + str(len(nd)) + ' != nodes count=' + str(len(nodes)))

if failed:
    for msg in failed:
        print('ERROR: viewer sanity failed: ' + msg, file=sys.stderr)
    print('  file: ' + str(vd_path), file=sys.stderr)
    sys.exit(1)
print('    viewer_data.json: OK (version=' + str(data['version']) + ', nodes=' + str(len(nodes)) + ', details=' + str(len(nd)) + ', fallbacks=' + str(data.get('detail_fallback_count', 0)) + ')')

# --- index.html ---
if not html_path.exists():
    print('ERROR: viewer sanity failed: ' + str(html_path) + ' does not exist', file=sys.stderr)
    sys.exit(1)
html = html_path.read_text()

required = [
    ('Remedy Brain Viewer',      'title/header'),
    ('id=\"viewer-data\"',       'data island id'),
    ('type=\"application/json\"','data island type'),
    ('static-fallback',          'initial render status'),
]
for needle, desc in required:
    if needle not in html:
        failed.append('index.html missing ' + desc + ': ' + repr(needle))

for ph in ('__VIEWER_DATA_JSON__', '__STATIC_FALLBACK__', '__JOB_SHORT_ID__', '__GENERATED_AT__'):
    if ph in html:
        failed.append('index.html contains unresolved placeholder: ' + repr(ph))

# Redaction sentinel scan: precise dangerous tokens must not appear in rendered output.
# These are metadata keys, uppercase sentinel markers, and exception strings that
# must never leak into viewer files.  Plain phrases such as the words artifact content
# or file content are NOT forbidden here: safe explanatory negations in viewer UI copy
# (e.g. "Does not include raw prompt, file content, ...") are intentional text.
forbidden_tokens = [
    'approval_reason',
    'diff_preview',
    'command_output',
    'raw_command_output',
    'DIFF_PREVIEW',
    'RAW_COMMAND_OUTPUT',
    'APPROVAL_REASON',
    'MUST_NOT_RENDER',
    'Traceback',
    'Exception:',
]
vd_text = vd_path.read_text()
for tok in forbidden_tokens:
    if tok in vd_text:
        failed.append('viewer_data.json contains forbidden redaction token: ' + repr(tok))
    if tok in html:
        failed.append('index.html contains forbidden redaction token: ' + repr(tok))

if failed:
    for msg in failed:
        print('ERROR: viewer sanity failed: ' + msg, file=sys.stderr)
    print('  file: ' + str(html_path), file=sys.stderr)
    sys.exit(1)
print('    index.html: OK')
" "${VIEW_DIR}"

    # -------------------------------------------------------------------------
    # 13. Summary
    # -------------------------------------------------------------------------
    echo ""
    echo "========================================"
    echo "PROJECT_ID = ${PROJECT_ID}"
    echo "JOB_ID     = ${JOB_ID}"
    echo "VIEW_PATH  = ${VIEW_PATH}"
    echo "remedy_smoke: PASSED"
    echo "========================================"
  )
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  remedy_smoke "$@"
fi
