"""The `mission` group's entries of the command catalog (F301, DECISION F301 D2).

Moved unchanged out of `apps/cli/command_catalog.py`, whose `_BASE_CATALOG` splices
`MISSION_COMMANDS` in at the group's own place, so the help keeps its order.
"""

from __future__ import annotations

from apps.cli.command_catalog_types import (
    _ALL_PROJECTS_FLAG,
    _JOB_ID,
    _JSON_OPT,
    _PROJECT_SCOPE_OPT,
    ArgDef,
    CommandEntry,
)

MISSION_COMMANDS: tuple[CommandEntry, ...] = (
    # ── mission (the F070 orchestrator, keyed on a mission id) ──────────
    CommandEntry(
        command_id="mission.run",
        group_id="mission",
        subcommand="run",
        description="Execute the F070 orchestrator for one mission's jobs. Stops on a terminal move, the iteration limit, a stop request or an escalation.",
        action_class="write_metadata",
        args=(
            ArgDef("run_id", "Mission id (F070 orchestrator) that owns the jobs"),
            ArgDef("--iterations", "Max iterations before the orchestrator stops", required=False, is_option=True),
            ArgDef("--no-llm", "Execute without a provider — reports the honest no_provider terminal", required=False, is_option=True, is_flag=True),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.report", "mission.watchdog"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.watchdog",
        group_id="mission",
        subcommand="watchdog",
        description="Evaluate a mission's autonomy tripwires over its jobs and report what fired, with the run's evidence behind it — read-only: it pauses nothing and answers no decision.",
        action_class="read_only",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.resume"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.handoff",
        group_id="mission",
        subcommand="handoff",
        description="Compose this mission's handoff artifact — dossier, checkpoint reference, open decisions, next intent and its jobs — so a fresh context can resume from it (F079).",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id that owns the jobs"),
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.watchdog"),
    ),
    CommandEntry(
        command_id="mission.report",
        group_id="mission",
        subcommand="report",
        description="Read-only morning-style report for a mission, built from its job's current run evidence.",
        action_class="read_only",
        args=(
            _JOB_ID,
            ArgDef("--markdown", "Render the report as markdown",
                   required=False, is_option=True, default="false"),
            _JSON_OPT,
        ),
        supports_json=True,
        may_mutate_repo=False,
        may_execute_commands=False,
        related=("mission.readiness", "mission.show"),
    ),

    # ── mission (F056: the persistent goal above a chain of jobs) ────────
    CommandEntry(
        command_id="mission.start",
        group_id="mission",
        subcommand="start",
        description="Create a mission — a persistent goal above the jobs that will serve it (explicit; never automatic).",
        action_class="write_metadata",
        args=(
            ArgDef("goal", "The persistent goal this mission exists for, before any job is created"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.list", "mission.show"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.list",
        group_id="mission",
        subcommand="list",
        description="List missions (scoped to the current project by default; unreadable records are skipped and counted).",
        action_class="read_only",
        args=(
            _PROJECT_SCOPE_OPT, _ALL_PROJECTS_FLAG,
            ArgDef("--status", "Only missions in this status: active, paused, achieved, abandoned, or planned (active, and no job started yet)", required=False, is_option=True),
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.start", "mission.show"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.continue",
        group_id="mission",
        subcommand="continue",
        description="Add the next job to a mission — its plan always begins with a task (a step) that verifies the previous job's Definition of Done.",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            ArgDef("next_step", "What this next job, under its mission, should do"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.start"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.plan",
        group_id="mission",
        subcommand="plan",
        description="Compile a mission's goal into a milestone plan (recompiles keep prior versions; refused once a milestone is in progress). Creates no jobs and starts nothing.",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            ArgDef("--no-llm", "Compile deterministically (no LLM provider call)", required=False, is_option=True, is_flag=True),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.start"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.show",
        group_id="mission",
        subcommand="show",
        description="Show one mission and its job chain, each job with the state the job store reports now, then every entry of the ledger its runs wrote (read-only).",
        action_class="read_only",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.list", "mission.start"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.contract",
        group_id="mission",
        subcommand="contract",
        description="Show a mission's contract — its acceptance criteria, each with the milestones of its plan it covers (read-only).",
        action_class="read_only",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "job.contract"),
        exit_codes=(0, 1, 2, 3),
    ),
    # Status transitions are their own explicit subcommands (R-0163): the verb
    # names the status, and nothing else in Remedy ever moves it.
    CommandEntry(
        command_id="mission.achieve",
        group_id="mission",
        subcommand="achieve",
        description="Mark a mission achieved — an explicit human judgement, never inferred from its jobs.",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.list"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.abandon",
        group_id="mission",
        subcommand="abandon",
        description="Mark a mission abandoned — the goal is dropped; its jobs and their run evidence stay.",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.list"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.pause",
        group_id="mission",
        subcommand="pause",
        description="Mark a mission paused — the goal still stands, work on its jobs does not.",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.show", "mission.list"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.resume",
        group_id="mission",
        subcommand="resume",
        description="Mark a mission active again — the pause on its jobs is lifted; the tripwire that caused it is not cleared.",
        action_class="write_metadata",
        args=(
            ArgDef("mission_id", "Mission id (or a unique prefix) that owns the jobs"),
            _PROJECT_SCOPE_OPT,
            _JSON_OPT,
        ),
        supports_json=True,
        related=("mission.pause", "mission.watchdog"),
        exit_codes=(0, 1, 2, 3),
    ),
    CommandEntry(
        command_id="mission.readiness",
        group_id="mission",
        subcommand="readiness",
        description="Read-only: is this job, under its mission, safe to execute unattended?",
        action_class="read_only",
        args=(_JOB_ID, _JSON_OPT),
        supports_json=True,
        may_mutate_repo=False,
        may_execute_commands=False,
        related=("mission.show", "mission.watchdog"),
    ),
)
